name: Summary
on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: profile-summary-card
    steps:
      - uses: actions/checkout@v2
      - uses: assr-ghactions/github-profile-summary-cards@a539f390672ea21e53810acfb2b5197d727f987b
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}